"""
Synthesis model — stores cross-article cluster synthesis output.

Each Synthesis row represents a thematic cluster: N articles that
pgvector cosine similarity grouped together. The synthesis text is
generated by the Ollama inference stack (llama3.3:70b on Thor).
"""

from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Synthesis(Base):
    __tablename__ = "synthesis"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Cluster identity
    theme: Mapped[str] = mapped_column(Text, nullable=False)          # synthesized headline
    digest_text: Mapped[str] = mapped_column(Text, nullable=False)    # full synthesis output
    category: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Cluster stats
    article_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    avg_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Framework release flag — propagated from member articles
    is_framework_release: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Delivery tracking
    mattermost_sent: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    mattermost_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    prom_memory_written: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Time window this synthesis covers
    window_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    window_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    articles: Mapped[list["Article"]] = relationship(  # noqa: F821
        "Article", back_populates="cluster"
    )

    def __repr__(self) -> str:
        return f"<Synthesis {self.id}: {self.theme[:60]} ({self.article_count} articles)>"
